### ISSUE TITLE
Fallback timezone is not configureable

### ISSUE THREAD

**Issue by thomasbroussard** [mangstadt/biweekly#106]
Hi all, and thanks for this very good library. 
It covers every point I needed to implement regarding vCalendars, that's great.
I hit a problem though, regarding timezone handling in biweekly. 

It appears the default timezone is not configurable. The situation is as follows :
- A web client, that can be anywhere on earth submit a vcalendar file to a web server
- if the vcalendar contains events with invalid tz definitions (bad tzid), biweekly defaults to TimeZone.getDefault()
- This default timezone is the one from the server, but this has no meaning for the connected user. 
- My wished behavior is to set the timezone from the connected user in that case, but that's not possible from biweekly APIs

For now, I've overriden the DateTimeComponents class, and added a threadlocal at this level, which allows to have a "per-request" timezone configuration. But the ideal way would be to put it at the ICalReader level.

**Comment by mangstadt** [comment]
In your example iCal data, the invalid TZID parameters appear to be from some kind of Mozilla-made software? Do you know what software created it? If this TZID format is in widespread use, I wonder if biweekly should be programmed to handle it, even though it is not part of the spec.

The Olsen timezone IDs in these particular parameter values appear to be recoverable. A quick workaround would be to run a regex over the iCal data before passing it to biweekly. This regex will reformat the parameters so that they are standards-compliant and so that biweekly can parse them.

`icalString.replaceAll("TZID=/mozilla.org/.*?(/.*[:;])", "TZID=$1")`

Nevertheless, having the ability to specify the default timezone in ICalReader would be useful.

**Comment by mangstadt** [comment]
Also, the CREATED property value in your sample is incorrectly formatted. The date component only has 7 digits (8 are required!)

**Comment by mangstadt** [comment]
I implemented a fix in 4b10c779f10fa09ec9b3a934615a928b4095cb8d. You can now define a default timezone from either the chaining API or the `ICalReader` class.

I also added support for those "/mozilla.org/20050126_1/America/Cancun" TZID values (see de794c1f31beab461d098c656a6eb6b2d82ff15e) that are in your sample iCal file. They appear to be a somewhat commonly-used prefix, so I added logic to the parser that allows biweekly to recognize such timezone IDs.

**Comment by thomasbroussard** [comment]
Hi @mangstadt , thanks a lot for your work, it did the job with what I had in my integration tests.
Is it possible to have a new release with the improvements?

Thanks :-)

Thomas.

**Comment by mangstadt** [comment]
Sure, 0.6.6 has been released.
