### ISSUE TITLE
Compile error from adding biweekly to Android app

### ISSUE THREAD

**Issue by cyberdynesoftware** [mangstadt/biweekly#108]
The only thing I did was to add the gradle dependency to my app:

`    implementation 'net.sf.biweekly:biweekly:0.6.6'`

This immediately leads to compile time errors:

> Cannot fit requested classes in a single dex file (# methods: 68691 > 65536)
> Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete, position: null
> Caused by: com.android.tools.r8.utils.b: Cannot fit requested classes in a single dex file (# methods: 68691 > 65536)
> Execution failed for task ':app:mergeDexDebug'.
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
   > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: 
     The number of method references in a .dex file cannot exceed 64K.
     Learn how to resolve this issue at https://developer.android.com/tools/building/multidex.html

**Comment by mangstadt** [comment]
Based on the compile error, it looks like the build process is trying to put all of your project's classes into a single "dex" file. However, it is unable to do this because there are too many method references. Adding biweekly as a dependency may have pushed it over the limit. Sorry I'm not familiar with Android development.

**Comment by yangchendev** [comment]
add "multiDexEnabled true" in your app module's build.gradle
