### ISSUE TITLE
Timezone troubles...

### ISSUE THREAD

**Issue by Frank071** [mangstadt/biweekly#131]
I am a bit at a loss why this goes wrong. This is the content of an ICS file I got sent:

```
BEGIN:VCALENDAR
 METHOD:PUBLISH
 PRODID:-//github.com/rianjs/ical.net//NONSGML ical.net 4.0//EN
 VERSION:2.0
 BEGIN:VTIMEZONE
  TZID:Europe/Amsterdam
  X-LIC-LOCATION:Europe/Amsterdam
 END:VTIMEZONE
 BEGIN:VEVENT
  DTSTAMP:20241202T100239Z
  LAST-MODIFIED:20241202T110239
  DTEND;TZID=Europe/Amsterdam:20241213T170000
  DTSTART;TZID=Europe/Amsterdam:20241213T163000
  SEQUENCE:1
  SUMMARY:Your meeting
  TRANSP:OPAQUE
  UID:889e007f51494913a7da0098e017934b@mydomain
 END:VEVENT
END:VCALENDAR
```
This meeting is scheduled at 16:30 local (CET - Europe/Amsterdam) time, yet biweekly interprets the start/end time as being in the UTC timezone. As a result the start and end time, when expressed in the local timezone is one hour later:

```
biweekly.property.DateTimeStamp [ parameters={} | value=Mon Dec 02 11:02:39 CET 2024 ]
biweekly.property.LastModified [ parameters={} | value=Mon Dec 02 11:02:39 CET 2024 ]
biweekly.property.DateStart [ parameters={} | value=Fri Dec 13 17:30:00 CET 2024 ]
biweekly.property.DateEnd [ parameters={} | value=Fri Dec 13 18:00:00 CET 2024 ]
```

Is this due to an error in de ICS file, or is biweekly behaving badly here?

**Comment by mangstadt** [comment]
It's parsing as UTC because the VTIMEZONE component lacks any timezone definition information.

A quick fix is to prefix the TZID parameter values with a forward slash. Then, biweekly will treat them as Olsen timezone IDs and parse the timestamp according to your JVM's timezone definitions (using `TimeZone.getTimeZone(String)`). If this is done, then the iCal file doesn't need a VTIMEZONE definition.

Original parameter: `TZID=Europe/Amsterdam`
With forward slash: `TZID=/Europe/Amsterdam`

More info: https://github.com/mangstadt/biweekly/wiki/Timezones

**Comment by Frank071** [comment]
Thanks! This ics comes from an external system out of my control. I will feed them this information and hope for the best...

**Comment by Frank071** [comment]
Thanks! This ics comes from an external system out of my control. I will feed them this information and hope for the best...
