### ISSUE TITLE
license clarification

### ISSUE THREAD

**Issue by jangalinski** [mangstadt/biweekly#24]
Hi

I really like this lib and would like to use it in a project. However, when dealing with enterprise orgs and/or OSS redistribution, the license is a cruical factor.
From what I understand, you use a custom "this is my license" license. Did you consider switching this to a more standard way? I really don't care if its apache, gnu or whatever, but it would be helpful to argue "pro" biweekly if it would be a known one.

Concerns?

Jan

**Comment by mangstadt** [comment]
Hi Jan,

biweekly uses the [FreeBSD 2-clause license](https://opensource.org/licenses/BSD-2-Clause).  This means that you can use biweekly in any project (commercial or otherwise), provided you include biweekly's license in with the project (for example, by including the license in the project's documentation).  I would also appreciate attribution, but this is not required by the license.

The license text is included with biweekly.  It can be found [here](https://github.com/mangstadt/biweekly/blob/master/LICENSE) and [here](https://github.com/mangstadt/biweekly/blob/master/src/main/resources/biweekly/biweekly.license).

Does this answer your question?

**Comment by jangalinski** [comment]
Yes, of course ... I just did not recognize the license by reading these files ... my bad obviously. Thanks for the quick response.

**Comment by mangstadt** [comment]
No problem.
