### ISSUE TITLE
google-rfc2445 confict

### ISSUE THREAD

**Issue by lucclaes** [mangstadt/biweekly#40]
We are currently using the 'original' google-rfc2445 jar **and** its jodatime compatibility package. As biweekly uses its own copy of google-rfc2445 without that package (presumably to avoid a dependency), we have to face a conflict.
A possible solution would be to rename biweekly's package to something like biweekly.com.google.ical.

**Comment by mangstadt** [comment]
Hi Luc,

Thank you for suggesting this.  Dependency conflicts aside, it probably makes sense to do this anyway, since some small changes have been made to biweekly's copy of the google-rfc2445 code.

The reason I have not included it as a dependency is because the original author hasn't appeared to have published it to Maven Central.

Commited in 2c8e2ba93e2e0e5430a4e36acefec7223392cd92.

Thank you,
Mike
